### ISSUE TITLE
%adl listaccounts is not working: 'DataLakeAnalyticsAccountManagementClient' object has no attribute 'account'

### ISSUE THREAD

**Issue by konjac** [Azure/Azure-Data-Service-Notebook#15]
**Describe the bug**
%adl listaccounts is not working

**To Reproduce**

%reload_ext adlmagics
AdlMagics initialized
%adl login --tenant microsoft.com
Waiting for user login...
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code G3Y73CEWX to authenticate.
User 'kuhuan@microsoft.com' logged in to tenant 'microsoft.com'
%adl listaccounts
Listing azure data lake analytics accounts...
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-69064daae67d> in <module>()
----> 1 get_ipython().run_line_magic('adl', 'listaccounts')

c:\program files\python36\lib\site-packages\IPython\core\interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2129                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2130             with self.builtin_trap:
-> 2131                 result = fn(*args,**kwargs)
   2132             return result
   2133 

<decorator-gen-126> in adl(self, line, cell)

c:\program files\python36\lib\site-packages\IPython\core\magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

c:\program files\python36\lib\site-packages\adlmagics\adlmagics_main.py in adl(self, line, cell)
     65 
     66         magic = self.__magics[cmd]
---> 67         return magic.execute(arg_string, cell)
     68 
     69     def __register_azure_magic(self, azure_magic_class):

c:\program files\python36\lib\site-packages\adlmagics\magics\adla\adla_accounts_listing_magic.py in execute(self, arg_string, content_string)
     15         self._write_line("Listing azure data lake analytics accounts...")
     16 
---> 17         adla_acounts = self._adla_service.retrieve_accounts(page_index = args.page_index, page_account_number = args.page_account_number)
     18 
     19         self._write_line("(%d) azure data lake analytics account(s) listed." % (len(adla_acounts)))

c:\program files\python36\lib\site-packages\adlmagics\services\adla_service_sdk_impl.py in retrieve_accounts(self, page_index, page_account_number)
     23         for sub in sub_client.subscriptions.list():
     24             dla_client = DataLakeAnalyticsAccountManagementClient(self.__token_service.credentials, sub.subscription_id)
---> 25             accounts.extend([AdlaAccount(account.name) for account in dla_client.account.list()])
     26 
     27         accounts.sort(key = lambda account: getattr(account, "name"))

AttributeError: 'DataLakeAnalyticsAccountManagementClient' object has no attribute 'account'

**Expected behavior**
Account should be listed

**Screenshots**

**Desktop (please complete the following information):**
 - OS
Win10
 - Browser 
chrome
 - Jupyter Version
Python 3.6.2, Jupyter notebook 5.5.0
 - ADS Notebook Version 
adlmagics-0.0.1

**Additional context**

**Comment by ruixinxu** [comment]
duplicate with #8

**Comment by gaoyangxiaozhu** [comment]
We have updated the dependencies associated with azure-data-lake-store in version 0.0.1, lead to the corresponding interface has changed. You may need to manually update the dependencies locally by typing
 `pip install -U azure-mgmt-datalake-store`
 in command prompt , and re-start you jupyter-notebook. 
 I think this problem related [issue#21](https://github.com/Azure/Azure-Data-Service-Notebook/issues/21) . In fact, the reason for this problem is that we updated the interface in version 0.0.1, but did not update the dependencies in the package provided to users. We will sovle this problem fundamentally in version 0.0.2, and you can see progress in  [issue#21](https://github.com/Azure/Azure-Data-Service-Notebook/issues/21)
