### ISSUE TITLE
%adl listaccounts does not list the account correctly

### ISSUE THREAD

**Issue by jingyanjingyan** [Azure/Azure-Data-Service-Notebook#16]
**Describe the bug**
"%adl listaccounts --page_index 0 --page_account_number -9" list 11 accounts
"%adl listaccounts" list 5 accounts

**To Reproduce**
1. %reload_ext adlmagics
2. %adl login --tenant microsoft.onmicrosoft.com
3. %adl listaccounts --page_index 0 --page_account_number -9
4. %adl listaccounts

**Expected behavior**
Should give out error in step3, and list all account in step4 as blow
![image](https://user-images.githubusercontent.com/36756024/41220944-6020e4b2-6d95-11e8-937a-3fb20764e067.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/36756024/41220876-41e98242-6d95-11e8-8acf-110fe9805c2e.png)
![image](https://user-images.githubusercontent.com/36756024/41220892-47baa692-6d95-11e8-9f5f-87222952843b.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: chrome
 - Jupyter Version: Python 3.6.2, Jupyter 4.4.0

**Additional context**

**Comment by wangxin921012** [comment]
There is a common problem that is not to verify or limit negative numbers. If negative numbers are invalid, they should be limited or declared.

**Comment by jingyanjingyan** [comment]
Repro at 07-25-2018
