### ISSUE TITLE
The keyword in warning message should be the same with command line

### ISSUE THREAD

**Issue by jingyanjingyan** [Azure/Azure-Data-Service-Notebook#24]
**Describe the bug**
The keyword in warning message should be the same with command line

**To Reproduce**
1. jobs1 = %adl listjobs --page_index 0 --page_job_number 100
Result: Warning "Parameter **account name** can not be None"
2. jobs1 = %adl listjobs --account devtooltelemetryadla --page_index -1 --page_job_number 100
Result: Warning "Parameter **skip** must be greater than 1"
3. jobs1 = %adl listjobs --account devtooltelemetryadla --page_index 0 --page_job_number -1
Result: Warning "Parameter **top** must be greater than 1"

**Expected behavior**
The keyword should be the same 
Command--------------warning message
account ----------------account name
page_index-------------skip
page_job_number------top

**Screenshots**
![image](https://user-images.githubusercontent.com/36756024/41266295-ee60fbe8-6e28-11e8-9907-07c0dad659f8.png)

**Desktop (please complete the following information):**
OS: Win10
Browser: chrome
Jupyter Version: Python 3.6.2, Jupyter 4.4.0

**Additional context**

**Comment by gaoyangxiaozhu** [comment]
@ruixinxu  @jingyanjingyan has been fixed with the issue [#28](https://github.com/Azure/Azure-Data-Service-Notebook/issues/28)

**Comment by gaoyangxiaozhu** [comment]
Sorry, i should not close it. I think may be should close this issue after merge the fix branch to master branch by vincent. @jingyanjingyan @ruixinxu  @iVincentFeng

**Comment by jingyanjingyan** [comment]
Repro at 07-25-2018
