### ISSUE TITLE
jobs.head(100) does not list all jobs 

### ISSUE THREAD

**Issue by jingyanjingyan** [Azure/Azure-Data-Service-Notebook#25]
**Describe the bug**
jobs.head(100) does not list all jobs 

**To Reproduce**
1. jobs = %adl listjobs --account devtooltelemetryadla --page_index 0 --page_job_number 100
2. jobs.head(100)

**Expected behavior**
list all jobs

**Screenshots**
![image](https://user-images.githubusercontent.com/36756024/41266488-a8a1c456-6e29-11e8-9117-14d4b9f10e5b.png)

**Desktop (please complete the following information):**
OS: Win10
Browser: chrome
Jupyter Version: Python 3.6.2, Jupyter 4.4.0

**Additional context**

**Comment by gaoyangxiaozhu** [comment]
still not show all info

**Comment by gaoyangxiaozhu** [comment]
fix done

**Comment by jingyanjingyan** [comment]
Repro at 07-25-2018
