### ISSUE TITLE
Confusing UI shows up in the result when set page_index to negative numbers

### ISSUE THREAD

**Issue by wangxin921012** [Azure/Azure-Data-Service-Notebook#30]
**Describe the bug**
Confusing UI shows up in the result when set page_index to negative numbers

**To Reproduce**
1. Run command "%adl listaccounts --page_index 0 --page_account_number 5", and set --page_index to a negative number.
2. Observe the displayed result.

**Expected behavior**
Not sure should displayed what, maybe should displayed 
![image](https://user-images.githubusercontent.com/40196669/41328838-d2dc26de-6efc-11e8-944a-835cd41eb7fc.png) as other no items searched displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/40196669/41328734-428801de-6efc-11e8-9cda-3714b6d0ae81.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Jupyter Version 5.5.0

**Comment by gaoyangxiaozhu** [comment]
i fix it and just let it show `[]`  @wangxin921012
