### ISSUE TITLE
The displayed sample csv/tsv file is poorly readable

### ISSUE THREAD

**Issue by wangxin921012** [Azure/Azure-Data-Service-Notebook#37]
**Describe the bug**
The displayed sample csv/tsv file is poorly readable

**To Reproduce**
1. Run command "%adl sample"
2. Set the value to "sample_data = %adl sample --account devtooltelemetryadls --file_path /Samples/AdlMagicsDemoSearchLogResult.csv --file_type csv --encoding utf-8 --row_number 20" (or you can set other files)
3. Observer the displayed results

**Expected behavior**
Should displayed these items in table as other command items displayed (like the below screenshot displayed), that can enhance its readability. 
![image](https://user-images.githubusercontent.com/40196669/41339129-b0b7adc4-6f26-11e8-8c5d-e3f21f11e291.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/40196669/41339087-92b2596e-6f26-11e8-882e-754281066521.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Jupyter Version 5.5.0

**Comment by iVincentFeng** [comment]
In the new version, after running following sample command
sample_data = %adl sample --account devtooltelemetryadls --file_path /Samples/Data/SearchLog.tsv --file_type tsv --encoding utf-8 --row_number 5

sample_data holds the result data as a DataFrame
