### ISSUE TITLE
AttributeError %adl list accounts

### ISSUE THREAD

**Issue by ruixinxu** [Azure/Azure-Data-Service-Notebook#8]
**Describe the bug**
Got an AttributeError when call the listaccounts command. Error msg:

Listing azure data lake analytics accounts...

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-9a827093e1df> in <module>()
----> 1 adl_accounts = get_ipython().run_line_magic('adl', 'listaccounts --page_index 0 --page_account_number 10')

c:\users\ruxu\documents\python3\lib\site-packages\IPython\core\interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2093                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2094             with self.builtin_trap:
-> 2095                 result = fn(*args,**kwargs)
   2096             return result
   2097 

<decorator-gen-126> in adl(self, line, cell)

c:\users\ruxu\documents\python3\lib\site-packages\IPython\core\magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

c:\users\ruxu\documents\python3\lib\site-packages\adlmagics\adlmagics_main.py in adl(self, line, cell)
     65 
     66         magic = self.__magics[cmd]
---> 67         return magic.execute(arg_string, cell)
     68 
     69     def __register_azure_magic(self, azure_magic_class):

c:\users\ruxu\documents\python3\lib\site-packages\adlmagics\magics\adla\adla_accounts_listing_magic.py in execute(self, arg_string, content_string)
     15         self._write_line("Listing azure data lake analytics accounts...")
     16 
---> 17         adla_acounts = self._adla_service.retrieve_accounts(page_index = args.page_index, page_account_number = args.page_account_number)
     18 
     19         self._write_line("(%d) azure data lake analytics account(s) listed." % (len(adla_acounts)))

c:\users\ruxu\documents\python3\lib\site-packages\adlmagics\services\adla_service_sdk_impl.py in retrieve_accounts(self, page_index, page_account_number)
     23         for sub in sub_client.subscriptions.list():
     24             dla_client = DataLakeAnalyticsAccountManagementClient(self.__token_service.credentials, sub.subscription_id)
---> 25             accounts.extend([AdlaAccount(account.name) for account in dla_client.account.list()])
     26 
     27         accounts.sort(key = lambda account: getattr(account, "name"))

AttributeError: 'DataLakeAnalyticsAccountManagementClient' object has no attribute 'account'

**To Reproduce**
Reproduce script : adl_accounts = %adl listaccounts --page_index 0 --page_account_number 10

**Expected behavior**
see a list of adla accounts under my azure subscription

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Windows 10 Enterprise
 - Browser: IE
 - Jupyter Version:  4.4.0
 - ADS Notebook Version : 0.0.1

**Additional context**

**Comment by iVincentFeng** [comment]
Fixed
